# Generated by Django 5.2.1 on 2025-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=20)),
                ('reg_age', models.IntegerField()),
                ('reg_loc', models.CharField(max_length=20)),
                ('reg_marks', models.IntegerField()),
                ('reg_date', models.DateField(max_length=20)),
            ],
        ),
    ]
