# Generated by Django 5.2.1 on 2025-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='reg_user',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
